### ISSUE TITLE
Add a refresh loader 

### ISSUE THREAD

**Issue by sayanee** [liccowee/webuildsg-android#1]
Thank you so much for the Android App! I only have one improvement to suggest 😄 👏 

Add a loader instead of the empty screen while it tries to fetch the data. Actually, it's a lot like the case of iOS: https://github.com/webuildsg/iOS/issues/9

**Comment by notthetup** [comment]
Not sure if it's fetching the data or what, but it shows a blank page on my device for a few seconds before it shows the frangment views.

![screenshot_20160616-231417](https://cloud.githubusercontent.com/assets/553140/16122149/9f363b2e-3418-11e6-9c0e-5f42f1d5f0d1.png)

**Comment by liccowee** [comment]
@notthetup It is because you compile the app by using Instant Run on Android Studio. The speed will be triple up if you install it as a release build.

**Comment by liccowee** [comment]
@sayanee Ya.. I will add a loading indicator and empty view for the list if nothing has been fetch. Thanks you for the suggestions 👍

**Comment by sayanee** [comment]
@liccowee after you close this issue, I think you can publish to the Play Store 🎉
